title: My Personal Site
description: A personal static site to talk about myself and display my projects
baseurl: ""
url: ""

collections:
  projects:
    output: true
  main-pages:
    output: true
    sort_by: order

include:
  - _pages

defaults:
  - scope:
      path: "projects"
      type: pages
    values:
      permalink: /projects/:basename/